import config from './config';
export default {
    DRIVER_PROJECT_ID: config.DRIVER_PROJECT_ID,
    DRIVER_CLIENT_EMAIL: config.DRIVER_CLIENT_EMAIL,
    DRIVER_PRIVATE_KEY: config.DRIVER_PRIVATE_KEY,
    CUSTOMER_PROJECT_ID: config.CUSTOMER_PROJECT_ID,
    CUSTOMER_CLIENT_EMAIL: config.CUSTOMER_CLIENT_EMAIL,
    CUSTOMER_PRIVATE_KEY: config.CUSTOMER_PRIVATE_KEY,
};
//# sourceMappingURL=fcm.config.js.map