import express from 'express';
import AuthRoutes from './userauth.routes';
import VehicleRoutes from './vehicle.routes';
import MiscRoutes from './miscellaneous.routes';
import ProfileRoutes from './useraddress.routes';
import DriverRoutes from './driver.routes';
import CustomerRoutes from './customer.routes';
import EmergencyContactRoutes from './emergencycontact.routes';
import RidesRoutes from './rides.routes';
import RatingRoutes from './ratings.routes';
import NotificationRoutes from './notifications.routes';
import WalletRoutes from './wallet.routes';
import PaymentRoutes from './payment.routes';
import BankAccountsRoutes from './bankaccount.routes';
const router = express.Router();
router.use('/auth', AuthRoutes);
router.use('/profile', ProfileRoutes);
router.use('/misc', MiscRoutes);
router.use('/rides', RidesRoutes);
router.use('/driver', DriverRoutes);
router.use('/customer', CustomerRoutes);
router.use('/vehicles', VehicleRoutes);
router.use('/emergency/contact', EmergencyContactRoutes);
router.use('/ratings', RatingRoutes);
router.use('/notifications', NotificationRoutes);
router.use('/wallets', WalletRoutes);
router.use('/payments', PaymentRoutes);
router.use('/bankaccounts', BankAccountsRoutes);
export default router;
//# sourceMappingURL=index.js.map