import express from 'express';
import AuthRoutes from './auth.routes';
import UsersRoutes from './userdetails.routes';
import LegalContentRoutes from './legalcontent.routes';
import DocumentsRoutes from './documents.routes';
import FAQsRoutes from './faqs.routes';
import VehicleTypesRoutes from './vehicleTypes.routes';
import CityRoutes from './citymanagement.routes';
import PricesRoutes from './pricemanagement.routes';
import RidesRoutes from './rides.routes';
import ContactUsRoutes from './contactus.routes';
import TestimonialRoutes from './testimonial.routes';
import NotificationsRoutes from './notifications.routes';
import ReferFriendRoutes from './referFriendssection.routes';
import BlogsRoutes from './blogs.routes';
import CategoryRoutes from './categories.routes';
import FeedbackRoutes from './feedback.routes';
import CouponsRoutes from './coupon.routes';
import CashoutRequestRoutes from './cashoutrequest.routes';
import WalletsRoutes from './wallets.routes';
import PaymentsRoutes from './payments.routes';
import ExportRoutes from './exportFile.routes';
import CareersRoutes from './career.routes';
import TaxesRoutes from './taxes.routes';
import AdditionalFeesRoutes from './additionalfees.routes';
import ReferralRoutes from './referral.routes';
const router = express.Router();
router.use('/auth', AuthRoutes);
router.use('/user', UsersRoutes);
router.use('/legalcontent', LegalContentRoutes);
router.use('/contact_us', ContactUsRoutes);
router.use('/documents', DocumentsRoutes);
router.use('/city', CityRoutes);
router.use('/prices', PricesRoutes);
router.use('/faqs', FAQsRoutes);
router.use('/rides', RidesRoutes);
router.use('/vehicle/types', VehicleTypesRoutes);
router.use('/testimonials', TestimonialRoutes);
router.use('/notifications', NotificationsRoutes);
router.use('/refer_friend', ReferFriendRoutes);
router.use('/categories', CategoryRoutes);
router.use('/blogs', BlogsRoutes);
router.use('/feedbacks', FeedbackRoutes);
router.use('/coupons', CouponsRoutes);
router.use('/cashout', CashoutRequestRoutes);
router.use('/wallets', WalletsRoutes);
router.use('/payments', PaymentsRoutes);
router.use('/exports', ExportRoutes);
router.use('/careers', CareersRoutes);
router.use('/taxes', TaxesRoutes);
router.use('/additionalfees', AdditionalFeesRoutes);
router.use('/referrals', ReferralRoutes);
export default router;
//# sourceMappingURL=index.js.map