import { Model } from 'sequelize';
import { ICityManagement } from './citymanagement.model';
import { IVehicleTypes } from './vehicleTypes.model';
import { ICategory } from './category.model';
export interface IPriceManagement {
    vehicleType: number;
    vehicleCategory: number;
    country: string;
    state: string;
    city: number;
    currency: string;
    currencySymbol: string;
    pricePerKg: number | null;
    pricePerKm?: number | null;
    pricePerMin?: number | null;
    minimumFareUSD: number;
    baseFareUSD: number;
    scheduleRideCharges: number;
    commissionPercentage: number;
    userCancellationTimeLimit: number;
    userCancellationCharges: number;
    waitingTimeLimit: number;
    waitingChargesUSD: number;
    nightCharges: boolean;
    priceNightCharges: number;
    nightStartTime?: string;
    nightEndTime?: string;
    status: 'active' | 'inactive';
    cityData?: ICityManagement;
    VehicleTypesData?: IVehicleTypes;
    vehicleCategoryData?: ICategory;
}
declare class PriceManagement extends Model implements IPriceManagement {
    id: number;
    vehicleType: number;
    vehicleCategory: number;
    country: string;
    state: string;
    city: number;
    currency: string;
    currencySymbol: string;
    pricePerKg: number | null;
    pricePerKm: number | null;
    pricePerMin: number | null;
    minimumFareUSD: number;
    scheduleRideCharges: number;
    baseFareUSD: number;
    commissionPercentage: number;
    userCancellationTimeLimit: number;
    userCancellationCharges: number;
    waitingTimeLimit: number;
    waitingChargesUSD: number;
    nightCharges: boolean;
    priceNightCharges: number;
    nightStartTime: string;
    nightEndTime: string;
    status: 'active' | 'inactive';
    cityData?: ICityManagement;
    vehicleTypeData?: IVehicleTypes;
}
export default PriceManagement;
