import { Model } from 'sequelize';
export interface ITransaction extends Model {
    id?: number;
    user: number;
    rideId: number;
    amount: number;
    transactionType: string;
    currency: string;
    transactionId: string;
    status: string;
    type: string;
    purpose: string;
    createdAt?: Date;
    updatedAt?: Date;
    tx_ref: string;
    flw_ref: string;
    device_fingerprint: string;
    charged_amount: number;
    app_fee: number;
    merchant_fee: number;
    processor_response: string;
    auth_model: string;
    ip: string;
    narration: string;
    payment_type: string;
    account_id: number;
    meta: object;
    amount_settled: number;
    customer: object;
    currentWalletbalance: number;
    method: string;
    category: string;
}
declare class Transactions extends Model implements ITransaction {
    id: number;
    user: number;
    rideId: number;
    amount: number;
    transactionType: string;
    currency: string;
    transactionId: string;
    status: string;
    purpose: string;
    type: string;
    createdAt: Date;
    updatedAt: Date;
    tx_ref: string;
    flw_ref: string;
    device_fingerprint: string;
    charged_amount: number;
    app_fee: number;
    merchant_fee: number;
    processor_response: string;
    auth_model: string;
    ip: string;
    narration: string;
    payment_type: string;
    account_id: number;
    meta: object;
    amount_settled: number;
    customer: object;
    currentWalletbalance: number;
    method: string;
    totalEarnings: string;
    category: string;
}
export default Transactions;
