"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const auth_routes_1 = __importDefault(require("./auth.routes"));
const userdetails_routes_1 = __importDefault(require("./userdetails.routes"));
const legalcontent_routes_1 = __importDefault(require("./legalcontent.routes"));
const documents_routes_1 = __importDefault(require("./documents.routes"));
const faqs_routes_1 = __importDefault(require("./faqs.routes"));
const vehicleTypes_routes_1 = __importDefault(require("./vehicleTypes.routes"));
const citymanagement_routes_1 = __importDefault(require("./citymanagement.routes"));
const pricemanagement_routes_1 = __importDefault(require("./pricemanagement.routes"));
const rides_routes_1 = __importDefault(require("./rides.routes"));
const contactus_routes_1 = __importDefault(require("./contactus.routes"));
const testimonial_routes_1 = __importDefault(require("./testimonial.routes"));
const notifications_routes_1 = __importDefault(require("./notifications.routes"));
const referFriendssection_routes_1 = __importDefault(require("./referFriendssection.routes"));
const blogs_routes_1 = __importDefault(require("./blogs.routes"));
const categories_routes_1 = __importDefault(require("./categories.routes"));
const feedback_routes_1 = __importDefault(require("./feedback.routes"));
const coupon_routes_1 = __importDefault(require("./coupon.routes"));
const cashoutrequest_routes_1 = __importDefault(require("./cashoutrequest.routes"));
const wallets_routes_1 = __importDefault(require("./wallets.routes"));
const payments_routes_1 = __importDefault(require("./payments.routes"));
const exportFile_routes_1 = __importDefault(require("./exportFile.routes"));
const career_routes_1 = __importDefault(require("./career.routes"));
const taxes_routes_1 = __importDefault(require("./taxes.routes"));
const additionalfees_routes_1 = __importDefault(require("./additionalfees.routes"));
const referral_routes_1 = __importDefault(require("./referral.routes"));
const router = express_1.default.Router();
router.use('/auth', auth_routes_1.default);
router.use('/user', userdetails_routes_1.default);
router.use('/legalcontent', legalcontent_routes_1.default);
router.use('/contact_us', contactus_routes_1.default);
router.use('/documents', documents_routes_1.default);
router.use('/city', citymanagement_routes_1.default);
router.use('/prices', pricemanagement_routes_1.default);
router.use('/faqs', faqs_routes_1.default);
router.use('/rides', rides_routes_1.default);
router.use('/vehicle/types', vehicleTypes_routes_1.default);
router.use('/testimonials', testimonial_routes_1.default);
router.use('/notifications', notifications_routes_1.default);
router.use('/refer_friend', referFriendssection_routes_1.default);
router.use('/categories', categories_routes_1.default);
router.use('/blogs', blogs_routes_1.default);
router.use('/feedbacks', feedback_routes_1.default);
router.use('/coupons', coupon_routes_1.default);
router.use('/cashout', cashoutrequest_routes_1.default);
router.use('/wallets', wallets_routes_1.default);
router.use('/payments', payments_routes_1.default);
router.use('/exports', exportFile_routes_1.default);
router.use('/careers', career_routes_1.default);
router.use('/taxes', taxes_routes_1.default);
router.use('/additionalfees', additionalfees_routes_1.default);
router.use('/referrals', referral_routes_1.default);
exports.default = router;
//# sourceMappingURL=index.js.map